baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Sable Ayala'
theme = "hermit-v2"
pygmentsCodefences = true
pygmentsUseClasses = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params.author]
  name = "Sable"

[taxonomies]
  tag = "tags"
  category = "categories"

# Enable to get proper Mathjax support
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  code_copy_button = true
  scrollToTop = true
  footerHideThemeName = true
  shareSocial = true

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/Sable-20"

  [[params.socialLinks]]
    name = "x"
    url = "https://x.com/theokaydev"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
